apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apacheds
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
      - name: apacheds
        image: "openmicroscopy/apacheds:0.5.0"
        envFrom:
        - secretRef:
            name: apacheds-config-private
        ports:
        - name: apacheds
          containerPort: 10389
      volumes:
      - name: apacheds-files
        persistentVolumeClaim:
          claimName: apacheds-volume
