apiVersion: v1
kind: PersistentVolume
metadata:
  name: apacheds-nfs
  labels:
    app: apacheds
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: idr-data.openmicroscopy.org
    path: /uod/idr/k8s-volumes/apacheds
