apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apacheds-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      app: apacheds
