apiVersion: v1
kind: Service
metadata:
  name: apacheds
  labels:
    name: apacheds
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 10389
      nodePort: 30389
  selector:
    app: apacheds
